services:
  db:
    image: mysql
    container_name: ai_companion
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
      MYSQL_DATABASE: companion
      MYSQL_USER: companion
      MYSQL_PASSWORD: password

    ports:
      - "3308:3306"
    volumes:
      - ./db:/var/lib/mysql

volumes:
  db:


